#!/usr/bin/env make -f
all:
	meld ~/Source/oss/android/mapsforge/Applications/Android/Samples/assets/renderthemes/rendertheme-v4.xml theme.xml

run:
	inkscape patterns/cemetery.svg

dbg:
	adb push . /storage/sdcard1/Android/data/org.pyneo.tabulae/files/maps/mapsforge/themes

